### ISSUE TITLE
Subset

### ISSUE THREAD

**Issue by MinuteswithMetrics** [junqiangchen/KiTS19-Challege#1]
Nice coding! Is there a way to set a numerical value for subset?

**Comment by junqiangchen** [comment]
> Nice coding! Is there a way to set a numerical value for subset?

first,calculate the all data number,such as 20000,split the data into 20% test data and 80% train data,so the value is the 4000.hope it help you.

**Comment by MinuteswithMetrics** [comment]
To make sure that I understand what your code is doing, are you downloading the whole training dataset? If so, is there a line in your code that I can change to only download a specific number of files?
