### ISSUE TITLE
visualize predictions

### ISSUE THREAD

**Issue by DecentMakeover** [junqiangchen/KiTS19-Challege#10]
Hi 

Is there a way to predict on a complete nii.gz case and produce a complete nii.gz file as a segmentation output ?

how would i go about doing this?

Thanks

**Comment by junqiangchen** [comment]
yeah，it's not difficult,first read nii.gz test data with simpleitk,then make patch images,put into model,get result masks,merge those masks,last write into nii.gz with simpleitk.

**Comment by DecentMakeover** [comment]
okay, ill check
