### ISSUE TITLE
error while running data3dprepare.py

### ISSUE THREAD

**Issue by dmksjfl** [junqiangchen/KiTS19-Challege#11]
Hi,

while i run your codes, data3dprepare.py, it reminds me that there are no such directory or file named /kits19segementation/200_12.bmp

while in your code, you write
 trainImage = "E:\junqiangchen\data\kits19\kits19segmentation\Image"

I would appreciate it if you could please tell me how to generate this file.

I run the project on Linux.

**Comment by junqiangchen** [comment]
follow process step,make sure input and output path exist.

**Comment by dmksjfl** [comment]
hi,
thanks for your help, i have figured out the issue concerning on data3dprepare.py
while i encounter problems with subset.py

Traceback (most recent call last):
  File "subset.py", line 119, in <module>
    main(sys.argv)
  File "subset.py", line 90, in main
    dataset, subset_size, method, subset_file, rest_file = process_options(argv)
  File "subset.py", line 48, in process_options
    subset_size = int(argv[i+1])
ValueError: invalid literal for int() with base 10: 'trainSegmentation.csv'

i use the subset.py like this, python subset.py 0 trainSegmentation.csv 200 trainset.csv test.csv

**Comment by junqiangchen** [comment]
i use the subset.py like this, python subset.py -s 1 trainSegmentation.csv 200 trainset.csv test.csv

**Comment by dmksjfl** [comment]
Thanks! It does work.
while i have another question with vnet3d_predict.py, in your code in util.py, you write
srcpath = "D:\Data\LIST\LITS-Challenge-Test-Data\\test-volume-" + str(38) + ".nii"
could you please tell me where can i download dataset in LITS-Challenge-Test-Data? or how did you generate it?
Thanks a lot for your kind help.

**Comment by junqiangchen** [comment]
test data have shared on baidu cloud disk,you can find download link.

**Comment by dmksjfl** [comment]
thanks, i will check. thanks for your help.
