### ISSUE TITLE
different

### ISSUE THREAD

**Issue by turkfuat** [junqiangchen/KiTS19-Challege#14]
hello,
Is there a difference between Kidney Segmentation and Kidney Tumor Segmentation?
Why does Kidney Tumor Segmentation have no results?

**Comment by junqiangchen** [comment]
the method is same,now  only have Kidney Segmentation.

**Comment by sindhuchava** [comment]
Hi junqiangchen,

Can you provide code for Tumor Segmentation?

**Comment by junqiangchen** [comment]
> Hi junqiangchen,
> 
> Can you provide code for Tumor Segmentation?

Hi,
Tumor Segmentation code is same as Kidney Segmentation.
