### ISSUE TITLE
tumordata2dprepare.py中路径设置

### ISSUE THREAD

**Issue by Xpangz** [junqiangchen/KiTS19-Challege#16]
我想请问1.2 Preprocess Kidney Tumor中第一步 tumordata2dprepare.py文件里的这个路径（35-38行）是如何设置的？我在开源的文件和数据集中没有找到Image和Mask文件夹（小白一枚，请见谅）
[图片]

**Comment by junqiangchen** [comment]
这两个文件夹需要手动生成一下即可
