### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PiotrowskiD** [junqiangchen/KiTS19-Challege#17]
Hi, I'd like to use you your project as a baseline for experiments in my master thesis. Would that be possible, and if yes could you add a license? Maybe a citation template too :)

**Comment by junqiangchen** [comment]
hi,
you can follow the template like this:
authors:
  - family-names: Chen
    given-names: junqiang
    orcid: https://github.com/junqiangchen/KiTS19-Challege
title: "KiTS19-Challege"
version: 2.0.0
date-released: 2019-11-18
