### ISSUE TITLE
intensity-values truncation?

### ISSUE THREAD

**Issue by samra-irshad** [junqiangchen/KiTS19-Challege#18]
Hi junqiangchen,

Thanks for this repo. Could you please tell why did you truncate the image intensities in 
'load_itkfilewithtrucation' function in corsedata2dprepare.py file? After truncating, the intensity values are rescaled to 0 and 255, so what was the reason for truncating before with 300 and -200?

**Comment by junqiangchen** [comment]
hi，the truncation value remove interference area，make the net better training.

**Comment by flamywhale** [comment]
I have the same problem. Why the truncating threshold is set between -200 and 300?  Why the lower threshold is negative values? @junqiangchen
