### ISSUE TITLE
Folder Directory

### ISSUE THREAD

**Issue by MinuteswithMetrics** [junqiangchen/KiTS19-Challege#2]
I set up my directory to mimic your folder tree for downloading the images. However, the images are not downloading into the folders. Instead they are being saves outside of the designated folder. For example, if the folder is not in the directory, it creates a folder and doesn't save the images in the sub-folder.  

```  
    proImage = "D:\Data\KiTS\kits19process\Image\\"
    proMask = "D:\Data\KiTS\kits19process\Mask\\"
    protumorImage = "D:\Data\KiTS\kits19tumorprocess\Image\\"
    protumorMask = "D:\Data\KiTS\kits19tumorprocess\Mask\\"
```

**Comment by junqiangchen** [comment]
> I set up my directory to mimic your folder tree for downloading the images. However, the images are not downloading into the folders. Instead they are being saves outside of the designated folder. For example, if the folder is not in the directory, it creates a folder and doesn't save the images in the sub-folder.
> 
> ```
>     proImage = "D:\Data\KiTS\kits19process\Image\\"
>     proMask = "D:\Data\KiTS\kits19process\Mask\\"
>     protumorImage = "D:\Data\KiTS\kits19tumorprocess\Image\\"
>     protumorMask = "D:\Data\KiTS\kits19tumorprocess\Mask\\"
> ```

there will generate many sub-folders,such as 0,1,2,3,4....,and in the sub-folders will have bmp image files

**Comment by MinuteswithMetrics** [comment]
Correct, However when I run the code it doesn't do that. The images will not save in the sub folder.

**Comment by junqiangchen** [comment]
> Correct, However when I run the code it doesn't do that. The images will not save in the sub folder.

but,i have generated successfully,make sure the proImage,proMask,protumorImage,protumorMask path is existed.

**Comment by MinuteswithMetrics** [comment]
They exists, I thought it was odd that the files was not saving in the appropriate folders.

**Comment by MinuteswithMetrics** [comment]
Here is an example of what I am talking about. 

![image](https://user-images.githubusercontent.com/25371067/56928885-c04a1100-6a9d-11e9-851f-c456d39ae322.png)

**Comment by MinuteswithMetrics** [comment]
I think the problem lies here:

```
        trainimagefile = proImage + str(seriesindex)
        trainMaskfile = proMask + str(seriesindex)
        if not os.path.exists(trainimagefile):
            os.makedirs(trainimagefile)
        if not os.path.exists(trainMaskfile):
            os.makedirs(trainMaskfile)

        tumorimagefile = protumorImage + str(seriesindex)
        tumorMaskfile = protumorMask + str(seriesindex)
        if not os.path.exists(tumorimagefile):
            os.makedirs(tumorimagefile)
        if not os.path.exists(tumorMaskfile):
            os.makedirs(tumorMaskfile)

```

**Comment by MinuteswithMetrics** [comment]
I figured out the problem.   

  ```   
        cv2.imwrite(trainimagefile + "//" + str(z) + ".bmp", src_kineryimg[z])
        cv2.imwrite(trainMaskfile + "//" + str(z) + ".bmp", seg_kineryimage[z])
  ```   

I had to change it from a ``` Backslash: \ to Forward Slash: /```
