### ISSUE TITLE
corsedata3dprepare.py generate patches

### ISSUE THREAD

**Issue by littlelk** [junqiangchen/KiTS19-Challege#20]
I think whenever the stridez >= 1 or stridewidth >= 1 or strideheight >= 1，wo should generate more than one patch. In line 25, I think it should be 
`    if stridez >= 1 or stridewidth >= 1 or strideheight >= 1:`

**Comment by junqiangchen** [comment]
you can modify it,but i set the if stridez >= 1 and stridewidth >= 1 and strideheight >= 1: that is for making sure input image size(x,y,z) is bigger than patch image size.

**Comment by turkfuat** [comment]
hi junqiangchen ; "corsedata3dprepare.py " I run the file but it only creates one .py file, what should I do?
can you help me
