### ISSUE TITLE
关于corsedata3dprepare.py

### ISSUE THREAD

**Issue by WeiDuan123** [junqiangchen/KiTS19-Challege#23]
hr_samples[0, 0:blockz, 0:block_width, 0:block_height] = image[0:rangz, 0:rangwidth, 0:rangheight]
hr_mask_samples[0, 0:blockz, 0:block_width, 0:block_height] = mask[0:rangz, 0:rangwidth, 0:rangheight]
您好，请问这里是将原图像的左上角128*128的地方返回吗，这样的话我得到的mask全部为0？

**Comment by junqiangchen** [comment]
> hr_samples[0, 0:blockz, 0:block_width, 0:block_height] = image[0:rangz, 0:rangwidth, 0:rangheight] hr_mask_samples[0, 0:blockz, 0:block_width, 0:block_height] = mask[0:rangz, 0:rangwidth, 0:rangheight] 您好，请问这里是将原图像的左上角128*128的地方返回吗，这样的话我得到的mask全部为0？

你好，仔细看一下代码。
