### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK ReadImage:

### ISSUE THREAD

**Issue by MinuteswithMetrics** [junqiangchen/KiTS19-Challege#4]
I'm so close to getting your code to ```data2dprocess.py``` to work. However, I keep running to the runtimeerror at the end of download. 

```
RuntimeErrorTraceback (most recent call last)
<ipython-input-10-c6b6b1f0d94c> in <module>()
    193 
    194 
--> 195 proKitsdata()

<ipython-input-10-c6b6b1f0d94c> in proKitsdata()
    146         file_image = kits_subset_path + image_name
    147         # 1 load itk image and truncate value with upper and lower
--> 148         src = load_itkfilewithtrucation(file_image, 300, -200)
    149         mask_path = kits_subset_path + mask_name
    150         seg = sitk.ReadImage(mask_path, sitk.sitkUInt8)

<ipython-input-10-c6b6b1f0d94c> in load_itkfilewithtrucation(filename, upper, lower)
     77     """
     78     # 1,tructed outside of liver value
---> 79     srcitkimage = sitk.Cast(sitk.ReadImage(filename), sitk.sitkFloat32)
     80     srcitkimagearray = sitk.GetArrayFromImage(srcitkimage)
     81     srcitkimagearray[srcitkimagearray > upper] = upper

/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.pyc in ReadImage(*args)
   8874 
   8875     """
-> 8876     return _SimpleITK.ReadImage(*args)
   8877 class ImageViewer(_object):
   8878     """

RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "data/kits19/imaging.nii.gz" does not exist.
```

Any idea on how to solve.

**Comment by junqiangchen** [comment]
> I'm so close to getting your code to `data2dprocess.py` to work. However, I keep running to the runtimeerror at the end of download.
> 
> ```
> RuntimeErrorTraceback (most recent call last)
> <ipython-input-10-c6b6b1f0d94c> in <module>()
>     193 
>     194 
> --> 195 proKitsdata()
> 
> <ipython-input-10-c6b6b1f0d94c> in proKitsdata()
>     146         file_image = kits_subset_path + image_name
>     147         # 1 load itk image and truncate value with upper and lower
> --> 148         src = load_itkfilewithtrucation(file_image, 300, -200)
>     149         mask_path = kits_subset_path + mask_name
>     150         seg = sitk.ReadImage(mask_path, sitk.sitkUInt8)
> 
> <ipython-input-10-c6b6b1f0d94c> in load_itkfilewithtrucation(filename, upper, lower)
>      77     """
>      78     # 1,tructed outside of liver value
> ---> 79     srcitkimage = sitk.Cast(sitk.ReadImage(filename), sitk.sitkFloat32)
>      80     srcitkimagearray = sitk.GetArrayFromImage(srcitkimage)
>      81     srcitkimagearray[srcitkimagearray > upper] = upper
> 
> /usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.pyc in ReadImage(*args)
>    8874 
>    8875     """
> -> 8876     return _SimpleITK.ReadImage(*args)
>    8877 class ImageViewer(_object):
>    8878     """
> 
> RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
> sitk::ERROR: The file "data/kits19/imaging.nii.gz" does not exist.
> ```
> 
> Any idea on how to solve.

the error is your inputdata path is not exist,make sure it.

**Comment by MinuteswithMetrics** [comment]
Thank you! I was able to get it to work.

**Comment by Shrutika994** [comment]
how were you able to solve it? i get the same problem.

**Comment by tekle-ai** [comment]
@MinuteswithMetrics how did you solve the error as I am facing the same problem. I never read .mhd and .raw images before, please.
