### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by turkfuat** [junqiangchen/KiTS19-Challege#5]
help me
data2prepare.py code executes json error ?

**Comment by junqiangchen** [comment]
what is error?

**Comment by turkfuat** [comment]
run :vnet3d_train.py

error : ValueError: The passed save_path is not a valid checkpoint: D:\KiTS19Challegeson-kodlar\log\segmeation\model\Vnet3d.pd-100000



________________________________
Gönderen: junqiangchen <notifications@github.com>
Gönderildi: 20 Mayıs 2019 Pazartesi 06:23
Kime: junqiangchen/KiTS19-Challege
Bilgi: turkfuat; Author
Konu: Re: [junqiangchen/KiTS19-Challege] json error (#5)


what is error?

**Comment by junqiangchen** [comment]
the error is don't have trained model,just remove the restore code.
