### ISSUE TITLE
subset

### ISSUE THREAD

**Issue by MinuteswithMetrics** [junqiangchen/KiTS19-Challege#7]
Can you show an example on how you run the subset.py? I'm unsuccessful after several attempts.

**Comment by junqiangchen** [comment]
you can read the readme,such as subeset -s 1 train.csv 200 sub1.csv sub2.csv

**Comment by MinuteswithMetrics** [comment]
I just was able to figure it out today. I read the readme file but somehow overlooked subset.py  Is there a reason why you chose .bmp versus .png or .jpeg? I was just curious of why you converted to .bmp. Thank you.
