### ISSUE TITLE
Training stats 

### ISSUE THREAD

**Issue by DecentMakeover** [junqiangchen/KiTS19-Challege#8]
Hi 

Could you please tell me for how many epochs you trained your model ? and what's the training accuracy you were able to achieve? I have trained it for 100 epochs but there is lot of fluctuation in the accuracy and it is not exceeding 50% is that like normal?

also i am running train vnet3d_train.py

**Comment by junqiangchen** [comment]
i try the epoch is 10,and dice accuracy is almost to 0.85.
