### ISSUE TITLE
not able to reproduce results

### ISSUE THREAD

**Issue by DecentMakeover** [junqiangchen/KiTS19-Challege#9]
Hi 

I have followed your steps but i am not able to reproduce the results.at epoch 20 i get the accuracy of 44 but then drops to 13 in the next epoch and then picks up to 34. 

Do you have any suggestion?

also wanted to confirm the time it take for you to train to 10 epochs, for me it takes less than a minute with a gpu, is it the same for you? i am running train_vnet3d.py

Thanks

**Comment by junqiangchen** [comment]
hello,i trained the model on one 1080Ti GPU,when you trained the model 20 epoch,you can calculate the dice of test result and groundtruth.
